### ISSUE TITLE
"Sentiment Bubble" (D3)

### ISSUE THREAD

**Issue by josephcc** [josephcc/SearchScapeVIz#4]
Show half filled sentiment bubble of different sizes (depending on number of terms) in overview mode

Something like this
https://hackernoon.com/using-machine-learning-to-visualize-customer-preferences-6a007cfb9b97

The size of the bubble shows the number of sentiment related terms, the colors show how many are positive and negative, weighted by AFINN.

We can also use this for per source visualization.

**Comment by nhahn** [comment]
We have the bubble now! Yay
